class AppStrings {
  /// ================== Arabic ==================
  static const Map<String, String> ar = {
    //login screen
    "username": "اسم المستخدم",
    "password": "كلمة المرور",
    "enter_username": "من فضلك أدخل اسم المستخدم",
    "enter_password": "من فضلك أدخل كلمة المرور",
    "babel_login": "بابل - تسجيل الدخول",
    "login_to_dashboard": "< تسجيل الدخول إلي لوحة التحكم",
    'forgot_password': 'نسيت كلمة السر ؟',
    // Sidebar / Menu
    'external_offices': 'المكاتب الخارجية',
    'dashboard': 'لوحة التحكم',

    'housing': 'الإيواء',
    'orders': 'الطلبات',

    'accounts': 'الحسابات',
    'accounts_external': 'الحسابات الخارجية',
    'accounts_employees': 'الموظفين',
    'accounts_statistics': 'الإحصائيات',
    'accounts_bonus': 'البونص',
    'accounts_expenses': 'المصروفات',
    'accounts_banks': 'البنوك والفيز',

    'users': 'المستخدمين',
    'countries': 'الدول',
    'contacts': 'جهات الاتصال',
    'history': 'سجل العاملات',
    "awaiting_delivery": "في انتظار التسليم",

    //---------------------------------dashboard_screen---------------------------------------------------------
    'dashboard_subtitle': 'نظرة عامة على النظام وإحصائيات الأداء',
    'dashboard_operation_pie_card_title': 'العاملات',
    'all_maids': 'كل العاملات',
    'accepted': "مقبولة",
    'under_processing': "تحت الاجراء",
    'rejected': "ملغاة",
    //offices_screen_details
    'add_new_contract': 'إضافة عقد نسائي جديد',
    "all_workers": "الكل",
    "under_process": "تحت الإجراء",
    "arrival": "الوصول",
    "finished": "منتهية",
    //-------------------add_new_contract_screen----------------------
    "office_details": "تفاصيل المكتب",
    "country": "الدولة",
    "office": "المكتب",

    "maid_details": "بيانات العاملة",
    "maid_name": "اسم العاملة",
    "enter_maid_name": "الرجاء إدخال اسم العاملة",
    "passport_number": "رقم جواز السفر",
    "enter_passport_number": "الرجاء إدخال رقم جواز السفر",
    "age": "العمر",
    "enter_age": "الرجاء إدخال العمر",
    "experience": "الخبرة",
    "religion": "الديانة",
    "salary": "الراتب",
    "enter_salary": "الرجاء إدخال الراتب",

    "sponsor_details": "بيانات الكفيل",
    "sponsor_name": "اسم الكفيل",
    "enter_sponsor_name": "الرجاء إدخال اسم الكفيل",
    "phone": "الجوال",
    "alternative_phone": "جوال بديل (اختياري)",
    "id_number": "رقم الهوية",
    "enter_id_number": "الرجاء إدخال رقم الهوية",

    "notes": " ملاحظات(اختياري)",
    "enter_additional_notes": "الرجاء إدخال أي ملاحظات إضافية هنا",
    "save_contract": "حفظ العقد",
    "cancel": "إلغاء",
    //--------------------------------------All Shelters Screen------------------------------------------------------------------------------------------------
    'housing-all': 'الإيواء - الكل',
    'waiting': 'في الانتظار',
    'waiting_delivery': 'في انتظار التسليم',
    'for_transfer': 'للتنازل',
    'escape': 'الهروب',
    'selsak_company': 'شركة سلسك (سكن)',
    'expired': 'منتهية',
    'for_deportation': 'للترحيل',
    'others': 'أخرى',
    "choose_approval_date": "من فضلك اختر تاريخ التصديق",

    //------------------Orders Screen-----------------------
    'orders_header': 'الطلبات',
    'search': 'بحث',
    'description': 'الوصف',
    'issue_fee': 'رسوم الإصدار',
    'transfer_fee': 'رسوم النقل',
    'employee': 'الموظف',
    'created_at': 'تاريخ الإضافة',
    'supervisor': 'المشرف',
    'updated_at': 'تاريخ التعديل',
    'status': 'الحالة',
    'actions': 'الإجراءات',
    'visa': "رقم التأشيرة",
    'accept': 'تأكيد',
    'index': 'عنصر',
    "male_agencies": "الوكالات الرجالية",

    //--------------users screen---------------------
    'users_header': 'المستخدمين',
    'full_name': 'الاسم الكامل',
    'user_name': 'اسم المستخدم',
    'save': 'حفظ',
    'choose_something': 'اختر شيئا',
    'employees': 'موظفين التعاقد',
    'agents': 'الوكلاء',
    'housing_employees': 'موظفين الإيواء',
    'supervisors': 'المشرفين',
    'add_employee': 'إضافة موظف',
    'add_agent': 'إضافة وكيل',
    'add_housing_employee': 'إضافة موظف إيواء',
    'whatsapp_messages': 'رسائل الواتساب',
    'name_en': 'الاسم بالإنجليزية',
    'name_ar': 'الاسم بالعربية',
    'content': 'المحتوى',
    'name': "الاسم",
    // Workers History DataTable
    'employer': 'صاحب العمل',
    'nationality': 'الجنسية',

    'add_new_country': 'إضافة دولة جديدة',
    'country_name_en': 'اسم الدولة بالإنجليزية',
    'country_name_ar': 'اسم الدولة بالعربية',
    'add_new_office': 'إضافة مكتب جديد',
    'no_offices_for_country': 'لا توجد مكاتب لهذه الدولة',
    'edit_office': 'تعديل المكتب',
    'office_name': 'اسم المكتب',
    'delete_office': 'حذف المكتب',
    'are_you_sure_you_want_to_delete_this_office':
        'هل أنت متأكد من حذف المكتب؟',
    'delete': 'حذف',
    'edit_country': 'تعديل الدولة',
    "confirm_delete": "تأكيد الحذف",
    "delete_country_confirm": "تأكيد حذف الدولة",
    'open_male_agencies': "الوكالات الرجالية المفتوحة",
    'female_agencies': "العقود النسائية",
    'open_female_agencies': "العقود النسائية المفتوحة",
    'gender': 'النوع',
    "male_worker_details": "بيانات العامل",
    'enter_name': "أدخل الاسم",
    'saved_successfully': 'تم الحفظ بنجاح',
    'male': 'ذكر',
    'female': 'أنثي',
    'passport': 'رقم الجواز',
    'sponsor': 'الكفيل',
    'mobile': 'الجوال',
    'visa_number': 'رقم التأشيرة',
    'approved': 'الحالة',
    'approved_': 'الموافقة',
    "notes_table": "ملاحظات",

    'added_by': 'أضيف بواسطة',
    'added_date': 'تاريخ الإضافة',
    'no_data_available': 'لا توجد بيانات في الجدول',
    'choose_religion': "اختر الديانة",
    'enter_phone': "الرجاء ادخال رقم الهاتف",
    'please_fix_errors': 'الرجاء اصلاح الاخطاء',
    'notes_too_long': 'الملاحظات طويلة جدا',
    'id_must_be_10_digits': 'رقم الهوية يجب أن يتكون من 10 أرقام',
    'invalid_id_number': 'رقم هوية خاطئ',
    'invalid_phone': 'رقم هاتف خاطئ',
    "choose_experience": "اختر الخبرة",
    'new': 'جديد',
    "error_happened": "حدث خطأ",
    "page": "صفحة",
    "btn_copy": "نسخ",
    "btn_csv": "CSV",
    "btn_excel": "Excel",
    "btn_pdf": "PDF",
    "btn_print": "طباعة",
    "btn_add_note": "إضافة ملاحظة",
    "btn_edit": "تعديل",
    "btn_cancel": "إلغاء",
    "btn_delete": "حذف",

    "col_no": "#",
    "col_worker_name": "اسم العاملة",
    "col_passport_no": "رقم جواز السفر",
    "col_age": "العمر",
    "col_sponsor": "الكفيل",
    "col_mobile": "الجوال",
    "col_national_id": "رقم الهوية",
    "col_visa_no": "رقم التأشيرة",
    "col_contract_date": "تاريخ العقد",
    "col_under_approval": "تحت الموافقة",
    "col_stamp": "الختم",
    "col_period": "الفترة",
    "col_worker_type": "نوع العاملة",
    "col_duration": "المدة",
    "col_sector": "القطاع",
    "col_arrival": "الوصول",
    "col_other_notes": "الملاحظات الأخرى",
    "col_delivery": "تسليم",
    "col_created_by": "تمت الإضافة بواسطة",
    "col_created_at": "تاريخ الإضافة",
    "col_actions": "الإجراءات",

    "showing_0_0_0": "عرض 0 إلى 0 من أصل 0 إدخالات",
    "showing": "عرض",
    "to": "إلى",
    "of": "من أصل",
    "entries": "إدخالات",
    'invalid_passport': "رقم جواز غير صالح",
    'add_new_agency': "اضافة وكالة رجالية جديدة",
    'phone_must_be_8_digits': 'رقم الهاتف يجب أن يتكون من 8 أرقام',
    "required": "مطلوب",
    'female_contracts': 'العقود النسائية',
    'open_female_contracts': 'العقود النسائية المفتوحة',
    "age_range_1_150": "العمر لازم يكون بين 1 و 150",

    "enter_contract_number": "ادخل رقم العقد",
    "invalid_contract_number": "رقم العقد غير صحيح",

    "enter_visa_number": "ادخل رقم الفيزا",
    "invalid_visa_number": "رقم الفيزا غير صحيح",

    "choose_visa_type": "اختر نوع الفيزا",
    "choose_contract_status": "اختر الحالة",
    "choose_experience_value": "اختر الخبرة",

    "contract_visa_details": "بيانات العقد والفيزا",

    "visa_type": "نوع الفيزا",
    "visa_type_full": "تأهيل شامل",
    "visa_type_normal": "عادية",

    "visa_number_hint": "VN-xxxx",

    "contract_number": "رقم العقد",
    "contract_number_hint": "CONT-xxxx",

    "contract_date": "تاريخ العقد",
    "contract_status": "حالة العقد",

    "status_new_contract": "عقد جديد",
    "status_under_process": "تحت الإجراء",
    "status_canceled": "ملغي",
    "status_on_arrival": "على الوصول",
    "status_finished": "منتهي",

    "religion_islam": "الإسلام",
    "religion_christian": "المسيحية",
    "religion_other": "أخرى",

    "experience_yes": "خبرة",
    "experience_no": "بدون خبرة",

    "approved_optional": "تمت الموافقة (اختياري)",
    "approval_date": "تاريخ الموافقة",

    "stamped_date_optional": "الختم (اختياري)",
    "flight_ticket_date_optional": "تذكرة الطيران (اختياري)",
    "arrival_date_optional": "تاريخ الوصول (اختياري)",

    "date_format_hint": "YYYY-MM-DD",
    "select_date": "اختر التاريخ",
    "show": "عرض",
    "no_data_available_in_table": "لا توجد بيانات متاحة في الجدول",
    "arrival_date": "تاريخ الوصول",
    "flight_ticket_date": "تاريخ تذكرة الطيران",
    "stamped_date": "تاريخ الختم",
    "yes": "تمت الموافقة",
    "no": "لم تتم الموافقة",
    "alternative_phone_table": "جوال بديل",
    "tracking_information": "معلومات المتابعة",
    "worker_information": "بيانات العاملة",
    "visa_information": "بيانات التأشيرة",
    "contract_information": "بيانات العقد",
    "sponsor_information": "بيانات الكفيل",
    "total_maids": "كل العاملات",
    "statistics": "الإحصائيات",
    "overview": "الرؤية",
    "worker_details": "بيانات العامل",
    "save_agency": "حفظ الوكالة",
    'edit': 'تعديل',
    'details': 'التفاصيل',
    "flight_ticket": "تذكرة الطيران",
    "stamp": "الختم",
    'arrival_orders': 'طلبات الوصول',
    "cancel_orders": "طلبات الإلغاء",
    "arrival_orders_subtitle": "طلبات الوصول",
    'arrival_note_named': 'معين بالاسم',
    'arrival_note_by_specs': 'حسب المواصفات',
    'choose_from': 'اختر من',
    'cancel_by_office': 'الإلغاء بواسطة المكتب',
    'cancel_by_client': 'الإلغاء بواسطة العميل',
    'cancelation_orders_subtitle': 'طلبات الإلغاء',
    'arrival_note_assigned': 'معين باسم',
    'arrival_note_specs': 'حسب المواصفات',
    'back': 'رجوع',
    'arrival_orders_history': 'سجل طلبات الوصول',
    'orders_history': 'سجل الطلبات',
    'orders_history_subtitle': 'سجل طلبات الوصول',
    'total': 'الإجمالي',
    'created_by': "الاضافة بواسطة",
    "Admin": "مسؤول النظام",
    "Manager": "مدير",
    "ReceptionEmployee": "موظف التعاقد",
    "AccommodationEmployee": "موظف الإيواء",
    "active": "نشط",
    "inactive": "غير نشط",
    "Deactivation": "إلغاء التنشيط",
    "Activation": "تنشيط",
    'contract_type': 'نوع العقد',
    'contract_type_named': 'معين بالاسم',
    'contract_type_specs': 'حسب المواصفات',
    'required_field': 'حقل مطلوب',
    'enter_password_to_confirm': "أدخل كلمة السر للتأكيد",
    'confirm_password': "تأكيد كلمة السر",
    'refresh': 'تحديث',
    'add_new_male_agency':'إضافة وكالة رجالية جديدة',
    'approved_by':'اعتمد بواسطة',

  };

  /// ================== English ==================
  static const Map<String, String> en = {
    'approved_by':'Approved by',
    'add_new_male_agency':'Add New Male Agency',
    'refresh': 'Refresh',
    'required_field': 'Required field',
    'enter_password_to_confirm': "Enter password to confirm",
    'confirm_password': "Confirm password",
    'contract_type': 'Contract Type',
    'contract_type_named': 'Named',
    'contract_type_specs': 'According to specifications',
    "deactivation": "Deactivation",
    "activation": "Activation",
    "active": "Active",
    "inactive": "Inactive",
    "Admin": "Admin",
    "Manager": "Manager",
    "ReceptionEmployee": "Contract employee",
    "AccommodationEmployee": "Accommodation employee",
    'total': 'Total',
    'edit': 'Edit',
    'details': 'Details',
    "flight_ticket": "Flight Ticket ",
    "stamp": "Stamp",
    'arrival_orders': 'Arrival Orders',
    "cancel_orders": "Cancelation Orders",
    "arrival_orders_subtitle": "Arrival Orders",
    'arrival_note_named': 'Named',
    'arrival_note_by_specs': 'According to specifications',
    'choose_from': 'Choose from',
    'cancel_by_office': 'Cancelation by Office',
    'cancel_by_client': 'Cancelation by Client',
    'cancelation_orders_subtitle': 'Cancelation Orders',
    'arrival_note_assigned': 'Assigned by name',
    'arrival_note_specs': 'By specifications',
    'back': 'Back',
    'arrival_orders_history': 'Arrival Orders History',
    'orders_history': 'Orders History',
    'orders_history_subtitle': 'Arrival Orders History',
    'created_by': "Created By",

    //--------Login screen---------
    "babel_login": "Babel - Login",
    "total_maids": "Total Maids",
    "statistics": "Statistics",
    "overview": "Overview",
    "username": "Username",
    "password": "Password",
    "enter_username": "Please enter username",
    "enter_password": "Please enter password",
    'login_to_dashboard': '> Login to Dashboard',
    'forgot_password': 'Forgot password ?',
    // Sidebar / Menu
    'external_offices': 'External Offices',
    'dashboard': 'Dashboard',

    'housing': 'Housing',
    'orders': 'Orders',
    "notes_table": "Notes",

    'accounts': 'Accounts',
    'accounts_external': 'External Accounts',
    'accounts_employees': 'Employees',
    'accounts_statistics': 'Statistics',
    'accounts_bonus': 'Bonus',
    'accounts_expenses': 'Expenses',
    'accounts_banks': 'Banks & Visas',

    'users': 'Users',
    'countries': 'Countries',
    'contacts': 'Contacts',
    'history': 'Workers History',

    //---------------------------------dashboard_screen---------------------------------------------------------
    'dashboard_subtitle': 'System overview and performance statistics',
    'dashboard_operation_pie_card_title': 'Maids',
    'all_maids': "All Maids",
    'accepted': "Accepted",
    'under_processing': "Under procedure",
    'rejected': "Canceled",
    //screen details -------------------------
    'add_new_contract': 'Adding a new contract',
    "all_workers": "All Workers",
    "under_process": "Under Process",
    "arrival": "Arrival",
    "finished": "Finished",
    "male_agencies": "Male Agencies",
    "awaiting_delivery": "Awaiting Delivery",

    //---------------------add new contract screen------------------------
    "office_details": "Office Details",
    "country": "Country",
    "office": "Office",

    "maid_details": "Maid Details",
    "maid_name": "Maid Name",
    "enter_maid_name": "Please enter maid name",
    "passport_number": "Passport Number",
    "enter_passport_number": "Please enter passport number",
    "age": "Age",
    "enter_age": "Please enter age",
    "experience": "Experience",
    "religion": "Religion",
    "salary": "Salary",
    "enter_salary": "Please enter salary",

    "sponsor_details": "Sponsor Details",
    "sponsor_name": "Sponsor Name",
    "enter_sponsor_name": "Please enter sponsor name",
    "phone": "Phone",
    "alternative_phone": "Alternative Phone(Optional)",
    "id_number": "ID Number",
    "enter_id_number": "Please enter ID number",

    "notes": "Notes (Optional)",
    "enter_additional_notes": "Please enter any additional notes here",
    "save_contract": "Save Contract",
    "cancel": "Cancel",

    //--------------------------------------All Shelters Screen------------------------------------------------------------------------------------------------
    'housing-all': 'Housing - Everyone',
    'waiting': 'Pending',
    'waiting_delivery': 'Waiting for Delivery',
    'for_transfer': 'For Transfer',
    'escape': 'Escape',
    'selsak_company': 'Selsak Company (Housing)',
    'expired': 'Expired',
    'for_deportation': 'For Deportation',
    'others': 'Others',
    //------------------Orders Screen-----------------------
    'orders_header': 'Orders',
    'search': 'Search',
    'description': 'Description',
    'issue_fee': 'Issue Fee',
    'transfer_fee': 'Transfer Fee',
    'employee': 'Employee',
    'created_at': 'Created At',
    'supervisor': 'Supervisor',
    'updated_at': 'Updated At',
    'status': 'Status',
    'actions': 'Actions',
    'visa': "Visa Number",
    'accept': 'Accept',
    'index': 'Index',

    //--------------users screen---------------------
    'users_header': 'Users',
    'full_name': 'Full Name',
    'user_name': 'User Name',
    'save': 'Save',
    'choose_something': 'choose Something',
    // Users Tabs
    'employees': 'Employees',
    'agents': 'Agents',
    'housing_employees': 'Housing Staff',
    'supervisors': 'Supervisors',
    'add_employee': 'Add Employee',
    'add_agent': 'Add Agent',
    'add_housing_employee': 'Add Housing Employee',
    'whatsapp_messages': 'WhatsApp Messages',
    'name_en': 'Name (English)',
    'name_ar': 'Name (Arabic)',
    'content': 'Content',
    'name': 'Name',
    // Workers History DataTable
    'employer': 'Employer',
    'nationality': 'Nationality',
    'add_new_country': 'Add New Country',
    "required": "Required",
    'country_name_en': 'Country name (English)',
    'country_name_ar': 'Country name (Arabic)',
    'add_new_office': 'Add New Office',
    'no_offices_for_country': 'No offices available for this country',
    'edit_office': 'Edit Office',
    'office_name': 'Office Name',
    'delete_office': 'Delete Office',
    'are_you_sure_you_want_to_delete_this_office':
        'Are you sure you want to delete this office?',
    'delete': 'Delete',
    'edit_country': 'Edit Country',
    "confirm_delete": "Confirm Delete",
    "delete_country_confirm": "Confirm Delete Country",
    'open_male_agencies': "Open Male Agencies",
    'female_agencies': "Female Contracts",
    'open_female_agencies': "Open Female Contracts",
    'gender': 'Gender',
    "male_worker_details": "Worker Details",
    'enter_name': "Enter Name",
    'saved_successfully': 'Saved Successfully',
    'male': 'Male',
    'female': 'Female',

    'passport': 'Passport No.',
    'sponsor': 'Sponsor',
    'mobile': 'Mobile',
    'visa_number': 'Visa Number',
    'approved': 'Status',
    'added_by': 'Added By',
    'added_date': 'Added Date',
    'no_data_available': 'No data available in table',
    'choose_religion': "Choose Religion",
    'enter_phone': "Please enter phone number",
    'please_fix_errors': 'Please fix errors',
    'notes_too_long': 'Notes too long',
    'id_must_be_10_digits': 'ID must be 10 digits',
    'invalid_id_number': 'Invalid ID number',
    'invalid_phone': 'Invalid phone number',
    "choose_experience": "Choose Experience",
    'new': 'New',

    "error_happened": "An error occurred",
    "page": "Page",
    "btn_copy": "Copy",
    "btn_csv": "CSV",
    "btn_excel": "Excel",
    "btn_pdf": "PDF",
    "btn_print": "Print",
    "btn_add_note": "Add note",
    "btn_edit": "Edit",
    "btn_cancel": "Cancel",
    "btn_delete": "Delete",

    "col_no": "#",
    "col_worker_name": "Worker name",
    "col_passport_no": "Passport No.",
    "col_age": "Age",
    "col_sponsor": "Sponsor",
    "col_mobile": "Mobile",
    "col_national_id": "National ID",
    "col_visa_no": "Visa No.",
    "col_contract_date": "Contract date",
    "col_under_approval": "Under approval",
    "col_stamp": "Stamp",
    "col_period": "Period",
    "col_worker_type": "Worker type",
    "col_duration": "Duration",
    "col_sector": "Sector",
    "col_arrival": "Arrival",
    "col_other_notes": "Other notes",
    "col_delivery": "Delivery",
    "col_created_by": "Created by",
    "col_created_at": "Created at",
    "col_actions": "Actions",

    "showing_0_0_0": "Showing 0 to 0 of 0 entries",
    "showing": "Showing",
    "to": "to",
    "of": "of",
    "entries": "entries",
    'invalid_passport': "Invalid passport number",
    'add_new_agency': "Add New Agency",
    'phone_must_be_8_digits': 'Phone must be 8 digits',
    'female_contracts': 'Female Contracts',
    'open_female_contracts': 'Open Female Contracts',
    "age_range_1_150": "Age must be between 1 and 150",

    "enter_contract_number": "Enter contract number",
    "invalid_contract_number": "Invalid contract number",

    "enter_visa_number": "Enter visa number",
    "invalid_visa_number": "Invalid visa number",

    "choose_visa_type": "Choose visa type",
    "choose_contract_status": "Choose contract status",
    "choose_experience_value": "Choose experience",

    "contract_visa_details": "Contract & Visa Details",

    "visa_type": "Visa type",
    "visa_type_full": "Full qualification",
    "visa_type_normal": "Normal",

    "visa_number_hint": "VN-xxxx",

    "contract_number": "Contract number",
    "contract_number_hint": "CONT-xxxx",

    "contract_date": "Contract date",
    "contract_status": "Contract status",

    "status_new_contract": "New contract",
    "status_under_process": "Under process",
    "status_canceled": "Canceled",
    "status_on_arrival": "On arrival",
    "status_finished": "Finished",

    "religion_islam": "Islam",
    "religion_christian": "Christianity",
    "religion_other": "Other",

    "experience_yes": "Experienced",
    "experience_no": "No experience",

    "approved_optional": "Approved (optional)",
    "approval_date": "Approval date",
    "stamped_date_optional": "Stamped (optional)",
    "flight_ticket_date_optional": "Flight ticket date (optional)",
    "arrival_date_optional": "Arrival date (optional)",

    "date_format_hint": "YYYY-MM-DD",
    "select_date": "Select date",
    "show": "Show",
    "no_data_available_in_table": "No data available in table",
    "choose_approval_date": "Please choose approval date",
    "arrival_date": "Arrival Date",
    "flight_ticket_date": "Flight Ticket Date",
    "stamped_date": "Stamped Date",

    "yes": "Approved",
    "no": "Not Approved",

    'approved_': 'Approving',
    "alternative_phone_table": "Alternative Phone",
    "tracking_information": "Tracking Information",
    "worker_information": "Worker Information",
    "visa_information": "Visa Information",
    "contract_information": "Contract Information",
    "sponsor_information": "Sponsor Information",
    "worker_details": "Worker Details",
    "save_agency": "Save Agency",
  };
}
